name: Deploy Ryne Worker

on:
  push:
    branches: [ main ]
    paths:
      - "api/**"
      - ".github/workflows/worker-deploy.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install deps
        run: npm ci

      - name: Deploy with Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          npx wrangler deploy --var COMMIT_SHA:${COMMIT_SHA}

      - name: Health check (non-fatal)
        continue-on-error: true
        run: |
          BASE="https://${{ secrets.CF_ACCOUNT_HANDLE }}.workers.dev"
          echo "Pinging: ${BASE}/health"
          curl -fsS "${BASE}/health" || true
